apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "reviews"
  description: "Reviews Service"
  tags:
    - java
  links:
    - url: https://devspaces.apps.cluster-m22mk.m22mk.sandbox2534.opentlc.com/?storageType=per-workspace#https://github.com/contract-first-camel/bookinfo-reviews-service
      title: OpenShift Dev Spaces
      icon: web
    - url: https://hawtio-online-hawtio-operator.apps.cluster-m22mk.m22mk.sandbox2534.opentlc.com/online/discover?namespace=system=bookinfo
      title: HawtIO
      icon: web
  annotations:
    github.com/project-slug: "contract-first-camel/bookinfo-reviews-service"
    backstage.io/kubernetes-id: "reviews"
    backstage.io/kubernetes-label-selector: "system=bookinfo"
    janus-idp.io/tekton : "reviews-service"
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/bookinfo
  providesApis: 
    - reviews